# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoClient 
pod 'Alamofire', '~> 4.5'
pod 'Web3'
pod 'Web3/ContractABI'

end
